spring.application.name: phrase-hackathon-llm-tm

server.port: 8080

# Actuator
management:
  endpoints.web.exposure.include: "*"
  endpoint.health.probes.enabled: true

# Open AI
open-ai:
  api-key: ${OPENAI_SECRET_API_KEY}
